/* Automaticaly generated by './build/build-entry.js'*/
import Row from '../packages/row/index.js';
import Col from '../packages/col/index.js';
import Button from '../packages/button/index.js';
import Input from '../packages/input/index.js';

const components = [
	Row,
	Col,
	Button,
	Input
];

const install = function (Vue, opts={}) {
	if (install.installed) return;
	components.map(component => {
		Vue.component(component.name, component);
	});
}

if (typeof window !== 'undefined' && window.Vue) {
	install(window.Vue);
}

export default{
	version: '1.0.0',
	install
};
